import type { Metadata } from 'next';
import '@/assets/styles/globals.css';
import Navbar from '@/components/Home/Navbar';
import AuthProvider from './(auth)/login/AuthProvider';
import Footer from '@/components/Home/Footer';
import { Toaster } from 'react-hot-toast';
export const metadata: Metadata = {
  title: 'GoMealSaver-v2',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <main className="min-h-screen px-4 sm:px-8 bg-[#0A0A0A] text-white py-16">
            {children}
          </main>
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
